export enum TopicCategoryEnum {
  "QUESTION_SET" = "QUESTION_SET",
  "EQUIVALENCE" = "EQUIVALENCE",
  "VOCABULARY" = "VOCABULARY",
  "SINGLE_BLANK" = "SINGLE_BLANK",
  "TWO_BLANK" = "TWO_BLANK",
  "THREE_BLANK" = "THREE_BLANK",
  "PASSAGE" = "PASSAGE",
  "IDIOMS_PHRASES" = "IDIOMS_PHRASES",
}
